/**Created by the LayaAirIDE,do not modify.*/
package ui {
	import laya.ui.*;
	import laya.display.*; 

	public class BoxUI extends View {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1084,"height":680,"cacheAs":"bitmap"},"child":[{"type":"Box","props":{"y":66,"centerX":0},"child":[{"type":"Image","props":{"y":37,"width":703,"skin":"comp/img_bg2.png","sizeGrid":"14,17,14,13","height":120}},{"type":"HBox","props":{"y":69,"x":27,"space":25,"align":"middle"},"child":[{"type":"Button","props":{"y":-3,"x":382,"width":200,"skin":"comp/button.png","sizeGrid":"20,24,28,30","labelSize":25,"labelPadding":"-2","label":"button3","height":60}},{"type":"Button","props":{"y":-1,"x":189,"width":200,"skin":"comp/button.png","sizeGrid":"20,24,28,30","labelSize":25,"labelPadding":"-2","label":"button2","height":60}},{"type":"Button","props":{"y":161,"width":200,"toggle":true,"skin":"comp/button.png","sizeGrid":"20,24,28,30","selected":true,"labelSize":25,"labelPadding":"-2","label":"button1","height":60}}]},{"type":"Label","props":{"y":-7,"text":"HBox横向适配","fontSize":30,"font":"SimHei","color":"#fdfdfd","centerX":-0.15625,"bold":true}}]},{"type":"Box","props":{"y":255,"x":198},"child":[{"type":"Image","props":{"y":41,"width":271,"skin":"comp/img_bg2.png","sizeGrid":"14,17,14,13","height":270}},{"type":"Box","props":{"y":61,"x":24},"child":[{"type":"Button","props":{"y":6,"x":9,"width":200,"toggle":true,"skin":"comp/button.png","sizeGrid":"20,24,28,30","selected":true,"labelSize":25,"labelPadding":"-3","label":"button1","height":60}},{"type":"Button","props":{"y":104,"x":28,"width":200,"skin":"comp/button.png","sizeGrid":"20,24,28,30","labelSize":25,"labelPadding":"-3","label":"button2","height":60}},{"type":"Button","props":{"y":167,"width":200,"skin":"comp/button.png","sizeGrid":"20,24,28,30","labelSize":25,"labelPadding":"-3","label":"button3","height":60}}]},{"type":"Label","props":{"y":-4,"text":"Box自由搭配","fontSize":30,"font":"SimHei","color":"#ffffff","centerX":0,"bold":true}}]},{"type":"Box","props":{"y":249,"x":613},"child":[{"type":"Label","props":{"x":41,"text":"VBox纵向适配","fontSize":30,"font":"SimHei","color":"#ffffff","bold":true}},{"type":"Image","props":{"y":48,"width":271,"skin":"comp/img_bg2.png","sizeGrid":"14,17,14,13","height":270}},{"type":"VBox","props":{"y":70,"x":40,"space":25,"align":"center"},"child":[{"type":"Button","props":{"x":9,"width":200,"toggle":true,"skin":"comp/button.png","sizeGrid":"20,24,28,30","selected":true,"labelSize":25,"labelPadding":"-3","label":"button1","height":60}},{"type":"Button","props":{"y":98,"x":28,"width":200,"skin":"comp/button.png","sizeGrid":"20,24,28,30","labelSize":25,"labelPadding":"-3","label":"button2","height":60}},{"type":"Button","props":{"y":161,"width":200,"skin":"comp/button.png","sizeGrid":"20,24,28,30","labelSize":25,"labelPadding":"-3","label":"button3","height":60}}]}]}]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);
		}
	}
}